<div id="menu">
  <a href="Bienvenida.php">Inicio</a>
  <a href="FormProductosINS.php">Insertar</a>
  <a href="FormProductosUPD.php">Actualizar</a>
  <a href="FormProductosDEL.php">Eliminar</a>
  <a href="FormProductosVER.php">Visualizar</a>
  <a href="FormProductosBajasVER.php">Listar Bajas</a>
  <a href="FormSincroComboPROD.php">Filtros Avanzados</a>
  <a href="FormProductosCategoriasINS.php">Menu Administrador</a>
  <a href="ProcesoLogout.php">Salir</a>

</div>